### ISSUE TITLE
Problem installing with Lazy.nvim (duplicate tag for "calltree-commands")

### ISSUE THREAD

**Issue by 2KAbhishek** [ldelossa/litee.nvim#109]
Trying to install this with Lazy.nvim causes problems with duplicate tag for "calltree-commands", here's the error:

```
  Failed (1)
    ○ litee.nvim   gh.nvim
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:51: Vim:E154: Duplicate tag "calltree-commands" in file /Users/abhishek/.local/share/nvim/lazy/litee.nvim/doc//calltree.txt
  
```

Version Info:

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

I can help fix this if you can give me some inputs! Looking forward to try this out

**Comment by 2KAbhishek** [comment]
I noticed that manually cloning the main branch fixes the problem, but lazy seems to pull the latest release tag `0.0.6` by default.

Doing a new release should fix the problem for a lot of users and more people can try this then!

**Comment by ldelossa** [comment]
Thanks for bringing this to my attention, I'm not a lazy-vim user. 

I created a v0.0.7 release off master: https://github.com/ldelossa/litee.nvim/releases/tag/v0.0.7

Does this solve the issue?

**Comment by 2KAbhishek** [comment]
Yes, it did, closing the issue now :)
