### ISSUE TITLE
redefine default ErrorMsg hi group

### ISSUE THREAD

**Issue by yorik1984** [ldelossa/litee.nvim#70]
https://github.com/ldelossa/litee.nvim/blob/391800d9e39176623d71c5e1b8ebbf17aea52816/lua/litee.lua#L70

**Comment by ldelossa** [comment]
This should be its own hi Group like the rest, is what youre saying right?

**Comment by yorik1984** [comment]
in dark mode it use own color:
https://github.com/ldelossa/litee.nvim/blob/391800d9e39176623d71c5e1b8ebbf17aea52816/lua/litee.lua#L46
But in light mode its redefine color from basic colosheme and change Error message color.

**Comment by ldelossa** [comment]
Got it, will fix.
