### ISSUE TITLE
Remapping call tree buffer actions?

### ISSUE THREAD

**Issue by jhchabran** [ldelossa/litee.nvim#78]
Hi! I just stumbled on this repo today after searching around for something like this, that's awesome to just find it 😊 and it works really well! 

How could I remap the [buffer specific actions](https://github.com/ldelossa/litee.nvim/blob/main/lua/litee/ui/buffer.lua#L158-L170)? Because it's done through the buffer handle, I don't know how I can override them.

Just some quick examples: 

- While I expand folds like everyone with `zo` in my buffers, in sidebars it's often also bound to `TAB` and my brain appears to be hardwired to it 😅. 
- Another one is `i` for hover whereas I have it bound on `[prefix]h` in my config and I'm not sure how I can rebind this. 

PS: There is a [dead link](https://github.com/ldelossa/litee.nvim/blob/main/doc/litee.nvim#L328) in the docs.

**Comment by ldelossa** [comment]
@jhchabran hey there.

thanks for the kind words. 

You should be able to create a keymap for the command very similarly to how the buffer local keymaps are set. 

Do you configure vim in Lua or Vimscript? 

P.s. thanks for the heads up about dead link. Gotta fix that.

**Comment by jhchabran** [comment]
@ldelossa You mean with an autocommand on the filetype `calltree` for example? Yes, I'm using lua :)

**Comment by ldelossa** [comment]
@jhchabran if you configure with lua can you simply to the following? 

    vim.api.nvim_buf_set_keymap(buffer_handle, "n", "<Tab>", ":LTExpand<CR>", opts)

**Comment by jhchabran** [comment]
> @jhchabran if you configure with lua can you simply to the following?
> 
> ```
> vim.api.nvim_set_keymap("n", "<Tab>", ":LTExpand<CR>", opts)
> ```
> 
> you can set opts to whatever you like.

Doing this will bind it globally, which is not something useful to do, especially on such a binding. Doing the following works as I want (I originally missed the `filetype` in the code I linked): 

```
vim.cmd(([[
autocmd Filetype calltree lua vim.api.nvim_set_keymap("n", "<Tab>", ":LTExpand<CR>", {})
]]))
```

I think that's worth documenting. I can submit a PR unless you had other plans for those bindings :)

**Comment by ldelossa** [comment]
You could also use the external commands which dont assume youre in a litee.nvim window, whicch are meant to be bound globally if you use litee often. The command is "LTExpandFiletree"

**Comment by ldelossa** [comment]
> > @jhchabran if you configure with lua can you simply to the following?
> > ```
> > vim.api.nvim_set_keymap("n", "<Tab>", ":LTExpand<CR>", opts)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you can set opts to whatever you like.
> 
> Doing this will bind it globally, which is not something useful to do, especially on such a binding. Doing the following works as I want (I originally missed the `filetype` in the code I linked):
> 
> ```
> vim.cmd(([[
> autocmd Filetype calltree lua vim.api.nvim_set_keymap("n", "<Tab>", ":LTExpand<CR>", {})
> ]]))
> ```
> 
> I think that's worth documenting. I can submit a PR unless you had other plans for those bindings :)

This is cool! But also the filetype will be changing to "litee" as the "calltree" name is now stale. And yes we should comment this, honestly i just did not think about it.

**Comment by ldelossa** [comment]
Going to close this for now. You have a PR solution. Can you implement this in the appropriate Litee plugin repos?

**Comment by jhchabran** [comment]
@ldelossa will do!
