### ISSUE TITLE
Project name suggestion

### ISSUE THREAD

**Issue by jhchabran** [ldelossa/litee.nvim#82]
Hi! 

This may be delicate and I apologize in advance if my suggestion seems blunt 🙏. 

Like I mentioned in #78, this project is what I've been looking for and I have been really happy to find out that someone took the time to do the work and made a great plugin with a nice feature set, so useful to explore large codebases. 

I almost missed the plugin because the name Litee suggests IDE features (which they all are) which is very general and may imply to the reader that it's one of those bloated plugins which tries too hard to reproduce a full IDE experience. As such it may be perceived wrongly to the experienced vimmer in a hurry. 

But that's absolutely not the case, this plugin addresses a specific issue which is to provide an interactive tree to explore callers and callees. And this is so damn useful. 

I believe that it would help the plugin adoption to name it accordingly, for example `calltree.nvim` or `calls-hierarchy.nvim`. I know that this was the previous name 😅 and I don't have the context for the name change, so my issue may come awkward. 

I also wonder if the file tree part shouldn't be removed entirely for the sake of not having to maintain it, as they are other popular projects covering the same goal and I suspect that most users are after the call tree part (but I may be totally wrong). 

If and only if you decide to agree with such a change, I can open a PR to rename everything to save you from having to handle that unglamorous kind of changes. 

I hope this suggestion does not come as anything else than a naming suggestion from someone who has a slight obsession for naming things and I'd like to state again that I very much appreciate the work being poured into bringing the plugin to existence.

**Comment by ldelossa** [comment]
https://github.com/ldelossa/litee.nvim/pull/80

After this merges, this repository will be *just* the library, and each feature will have its own repository,
So there will be a "litee-calltree", "litee-symboltree", and "litee-filetree" repository. 

This repository will no longer couple all the tools together and will only be a "library" for implementing "IDE-lite" features. 

I think with those changes, the naming becomes more intuitive.

**Comment by jhchabran** [comment]
Oh, I missed that PR and your Reddit post! And thank you for taking the time to explain the details 🙏

**Comment by ldelossa** [comment]
NP.
