### ISSUE TITLE
Launch modules on LTPanel

### ISSUE THREAD

**Issue by javeoff** [ldelossa/litee.nvim#91]
I repeated this [configuration](https://github.com/ldelossa/dotfiles/blob/95ca90fb73/nvim/lua/configs/litee.lua), read the documentation of plugin and yet don't understand how to get functionality like in readme screenshot.

Please, can you give me an example of plugin configuration with modules in vertical side-by-side layout?

I prefer, plugins must be included in the **state** option, but what do parameters mean inside?

**Comment by ldelossa** [comment]
Plugins will only show up in the panel when "opened" 

For example, if youre using "calltree" then you must issue a "symbols outline" request. First. 

Id start with using a single plugin then using multiple should make sense

**Comment by javeoff** [comment]
`:LTOpenFileTree` - is working, but any other plugins don't react to my commands

For example, `:LTOpenToSymbolTree` `:LTOpenToCallTree` don't send response and not showing in LTPanel

I had symbols outline plugin, and tried to disable that. I just want to repeat configuration, where all functions currently work to customize for myself

**Comment by ldelossa** [comment]
Yes, thats intended. Those commands have nothing to open UNTIL you issue a "vim.lsp.buf.document_outline()" call for example. 

You must issue the LSP commands to first create the state necessary to display "Calltree" snd "Symboltree" UI in the panel

**Comment by M1Sports20** [comment]
I seem to not understand how to use this either.
I don't have a function called :lua vim.lsp.buf.document_outline()

I have the require lines and have working LSP for my project.  I get an error message when I issue :LTPanel. :LTOpenToSymboltree seems to not doing anything.

I am sure the project is fine, just haven't figured out how to use it yet.

**Comment by kagbodji** [comment]
were you able to resolve this @M1Sports20 ? I can't figure out how to use this plugin either... issuing `:lua vim.lsp.buf.document_outline()` gives me the same error you mentioned in your last comment. @ldelossa could you please comment on what we might be doing wrong here?

**Comment by ldelossa** [comment]
sorry the function actually is:

```
document_symbol()                              *vim.lsp.buf.document_symbol()*
                Lists all symbols in the current buffer in the quickfix
                window.
```

when you issue this, if you have "litee-symboltree.nvim" correctly installed, it will open the UI.
