### ISSUE TITLE
Conditional settings relativenumber, signcol, etc.

### ISSUE THREAD

**Issue by tobealive** [ldelossa/litee.nvim#97]
This feels like a super noobish question, and I'm already a bit sorry for bothering, but I couldn't figure it out until now unfortunately.

Could someone maybe give a hint how to disable settings like the `relativenumber`, and `signcolum` for the panel (those are still show when they are not set `=number`, like it is in litees config files)? For now I added it to the `set_win_opts()` in the plugin data files but theres probably a better solution to this.

Couldn't target those with filetype autocmds :/

---

I forked it for now and use it that way. But I think this is probably the intended default setting to have those disabled in the panel view as the current configuration is already doing it, but it got reenabled by the settings I'm using. Adding those two lines of code is not  really an accomplishment but if you like I'll submit a PR.

**Comment by ldelossa** [comment]
Youre seeing line numbers and signs in the litee panels? Ive never experienced this before.

**Comment by tobealive** [comment]
That indeed sounds like it shouldn't be the case, haha. Yeah, I checked your dotfiles to find what I might be doing wrong. They contain [`set signcolumn=number`](https://github.com/ldelossa/dotfiles/blob/ec0316cb88d103d2177596900118fdfe2d1293b3/config/nvim/init.vim#L41) and relative number is not used. Then disabling just `number` in the win_opts removes all of it.
